apiVersion: apps/v1
kind: Deployment
metadata:
 name: db-deployment
 labels:
  app: todo
spec:
  replicas: 1
  selector:
   matchLabels:
    name: mongo
  template:
   metadata:
    labels:
      app: todo
      name: mongo
   spec:
    containers:
    - name: mongo
      image: mongo:5.0
      resources:
      ports:
      - containerPort: 27017
      volumeMounts:
       - name:  mongo-storage
         mountPath: /data/db
    volumes:  
     - name: mongo-storage
       persistentVolumeClaim:
        claimName: db-pvc

