apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
  labels:
    app: todo
spec:
  selector:
    matchLabels:
      name: web
  template:
    metadata:
      labels:
        name: web
        app: todo
    spec:
      containers:
      - name: myweb
        image: korayayakin/jsapp:v1
        ports:
        - containerPort: 3000
        env:
          - name: "DBHOST"
            value: db-service
        resources:
          limits:
            memory: 500Mi
            cpu: 100m
          requests:
            memory: 250Mi
            cpu: 80m